import httpx
import urllib.parse
from pyrogram import Client, filters, enums
from pyrogram.enums import ChatAction
from config import Config
from ISTKHAR_CHATBOT.modules.db import get_user_context, save_user_context, reset_user_context

# --- Text AI Engine (OpenRouter) ---
async def call_openrouter(messages: list) -> str:
    if not Config.OPENROUTER_KEYS:
        return "❌ **API Error:** OpenRouter keys Config/Env file mein nahi mil rahi hain!"
    
    url = "https://openrouter.ai/api/v1/chat/completions"
    payload = {"model": "openai/gpt-4o-mini", "messages": messages}

    for idx, api_key in enumerate(Config.OPENROUTER_KEYS):
        headers = {
            "Authorization": f"Bearer {api_key}",
            "HTTP-Referer": f"https://t.me/{Config.SUPPORT_GRP}", 
            "X-Title": "IstkharChatbot"                     
        }
        try:
            async with httpx.AsyncClient() as client:
                res = await client.post(url, json=payload, headers=headers, timeout=15.0)
                res.raise_for_status()
                return res.json()['choices'][0]['message']['content']
        except Exception as e:
            print(f"[LOG] API Key {idx + 1} Failed: {e}")
            continue
            
    return "❌ **Error:** All AI API keys failed. Limit khatam ho sakti hai."

# --- THE ULTIMATE SEAMLESS HANDLER (Crash-Proof) ---
@Client.on_message(filters.text & ~filters.bot, group=1)
async def seamless_ai_handler(client: Client, message):
    try:
        user_input = message.text
        is_group = message.chat.type in [enums.ChatType.GROUP, enums.ChatType.SUPERGROUP]
        
        # ==========================================
        # 🎨 1. IMAGE GENERATION LOGIC
        # ==========================================
        image_trigger_words = ["draw", "generate image", "create image", "photo of", "picture of", "imagine", "banao"]
        is_image_request = any(user_input.lower().startswith(word) for word in image_trigger_words) or user_input.startswith(("/draw", "/image"))

        if is_image_request:
            prompt = user_input
            for cmd in ["/draw", "/image", "draw", "generate image", "create image", "imagine", "photo of", "picture of"]:
                if prompt.lower().startswith(cmd):
                    prompt = prompt[len(cmd):].strip()
                    break
            
            if not prompt:
                await message.reply_text("💡 **Kya banau?**\nExample: `draw a cute cat flying in space`")
                return
                
            await client.send_chat_action(message.chat.id, ChatAction.UPLOAD_PHOTO)
            
            try:
                encoded_prompt = urllib.parse.quote(prompt)
                image_url = f"https://image.pollinations.ai/prompt/{encoded_prompt}?width=1024&height=1024&nologo=true"
                await message.reply_photo(photo=image_url, caption=f"🎨 **Generated by AI**\n💭 Prompt: `{prompt}`\n✨ Made by @{Config.OWNER_USERNAME}")
            except Exception as e:
                await message.reply_text("❌ Sorry, image generate karne mein problem aayi.")
            return

        # ==========================================
        # 🧠 2. SMART TEXT CHAT LOGIC (BUG FIXED)
        # ==========================================
        should_reply = False
        
        if user_input.startswith(("/", ".")):
            cmd = user_input.split()[0].lower()
            if any(c in cmd for c in ["ai", "ask", "chatgpt", "gemini"]):
                should_reply = True
                user_input = " ".join(user_input.split()[1:])
                if not user_input and message.reply_to_message:
                    user_input = message.reply_to_message.text
            else:
                # IMPORTANT: Ignore other bot commands (like /start) so AI doesn't break them!
                return 
        else:
            if not is_group:
                should_reply = True 
            elif is_group and message.reply_to_message and message.reply_to_message.from_user.id == client.me.id:
                should_reply = True 

        if not should_reply or not user_input or not user_input.strip():
            return

        await client.send_chat_action(message.chat.id, ChatAction.TYPING)
        user_id = message.from_user.id
        
        # ==========================================
        # 👑 3. AI BRAIN & MEMORY (CRASH-PROOF)
        # ==========================================
        try:
            history = await get_user_context(user_id)
        except Exception as e:
            print(f"[DB ERROR]: {e}")
            history = [] # Agar MongoDB fail bhi ho jaye, toh AI chalna band nahi hoga!

        if not history:
            system_prompt = (
                f"You are an advanced, extremely empathetic, and highly intelligent AI created by THE SHIV (@{Config.OWNER_USERNAME}).\n"
                "STRICT RULES:\n"
                "1. NO ABUSES: Never use bad words, insults, or abusive language.\n"
                "2. EMPATHY: If a user is sad, depressed, or angry, be a supportive friend. Comfort them, listen to them, and spread positivity.\n"
                "3. ACCURACY: Provide 100% correct and logical answers to their questions.\n"
                "4. STYLISH FONTS: If the user asks you to write in a stylish font, use Unicode stylized characters.\n"
                "5. LANGUAGE: Reply warmly in Hindi, Hinglish, or English, matching the user's language."
            )
            history.append({"role": "system", "content": system_prompt})
            
        history.append({"role": "user", "content": user_input})
        
        ai_reply = await call_openrouter(history)

        # Agar OpenRouter se "❌ API Error" wapas aaya hai
        if ai_reply.startswith("❌"):
            await message.reply_text(ai_reply)
            return

        history.append({"role": "assistant", "content": ai_reply})
        
        try:
            await save_user_context(user_id, history)
        except Exception as e:
            print(f"[DB SAVE ERROR]: {e}")
            
        await message.reply_text(ai_reply, quote=True)

    except Exception as e:
        # Ab agar koi bhi line phat ti hai, toh bot chup nahi baithega, error batayega!
        print(f"[CRITICAL ERROR]: {e}")
        await message.reply_text(f"⚠️ **System Error:** `Bot ke code me issue hai: {e}`\nCheck Logs!")

# --- Memory Reset Command ---
@Client.on_message(filters.command(["reset", "history"], prefixes=[".", "/"]))
async def reset_command_handler(client, message):
    user_id = message.from_user.id
    try:
        await reset_user_context(user_id)
        await message.reply_text("🧠 **Chat History Cleared!**\n\nMeri memory fresh ho gayi hai. Boliye, kya madad karu?")
    except Exception as e:
        await message.reply_text("⚠️ Database se memory delete nahi ho paayi.")
