import httpx
import urllib.parse
from pyrogram import Client, filters, enums
from pyrogram.enums import ChatAction
from config import Config
from ISTKHAR_CHATBOT.modules.db import get_user_context, save_user_context, reset_user_context

# --- AI Engine (OpenRouter - No MukeshAPI) ---
async def call_openrouter(messages: list) -> str:
    if not Config.OPENROUTER_KEYS:
        raise Exception("OpenRouter Keys Missing from config!")
    url = "https://openrouter.ai/api/v1/chat/completions"
    payload = {"model": "openai/gpt-4o-mini", "messages": messages}

    for idx, api_key in enumerate(Config.OPENROUTER_KEYS):
        headers = {
            "Authorization": f"Bearer {api_key}",
            "HTTP-Referer": f"https://t.me/{Config.SUPPORT_GRP}", 
            "X-Title": "IstkharChatbot"                     
        }
        try:
            async with httpx.AsyncClient() as client:
                res = await client.post(url, json=payload, headers=headers, timeout=15.0)
                res.raise_for_status()
                return res.json()['choices'][0]['message']['content']
        except Exception as e:
            continue
    raise Exception("All AI Keys Failed.")

# --- THE SEAMLESS HANDLER (Text + Image) ---
@Client.on_message(filters.text & ~filters.bot)
async def seamless_ai_handler(client: Client, message):
    user_input = message.text
    is_group = message.chat.type in [enums.ChatType.GROUP, enums.ChatType.SUPERGROUP]
    
    # ==========================================
    # 🎨 1. IMAGE GENERATION LOGIC
    # ==========================================
    image_trigger_words = ["draw", "generate image", "create image", "photo of", "picture of", "imagine", "banao"]
    is_image_request = any(user_input.lower().startswith(word) for word in image_trigger_words) or user_input.startswith(("/draw", "/image"))

    if is_image_request:
        prompt = user_input
        # Remove trigger words to get the pure prompt
        for cmd in ["/draw", "/image", "draw", "generate image", "create image", "imagine", "photo of", "picture of"]:
            if prompt.lower().startswith(cmd):
                prompt = prompt[len(cmd):].strip()
                break
        
        if not prompt:
            await message.reply_text("💡 **Kya banau?**\nExample: `draw a cute cat flying in space`")
            return
            
        await client.send_chat_action(message.chat.id, ChatAction.UPLOAD_PHOTO)
        
        try:
            encoded_prompt = urllib.parse.quote(prompt)
            image_url = f"https://image.pollinations.ai/prompt/{encoded_prompt}?width=1024&height=1024&nologo=true"
            
            await message.reply_photo(
                photo=image_url, 
                caption=f"🎨 **Generated by AI**\n💭 Prompt: `{prompt}`"
            )
        except Exception as e:
            await message.reply_text("❌ Sorry, image generate karne mein problem aayi.")
        return

    # ==========================================
    # 🧠 2. SMART TEXT CHAT LOGIC
    # ==========================================
    should_reply = False
    
    # Private chat bina command ke
    if not is_group:
        should_reply = True 
        
    # Group me bot ko reply kiya ho
    elif is_group and message.reply_to_message and message.reply_to_message.from_user.id == client.me.id:
        should_reply = True 
        
    # Command use ki ho (/ask, /ai, /gemini)
    elif user_input.startswith((".", "/")):
        cmd = user_input.split()[0].lower()
        if any(c in cmd for c in ["ai", "ask", "chatgpt", "gemini"]):
            should_reply = True
            user_input = " ".join(user_input.split()[1:])
            if not user_input and message.reply_to_message:
                user_input = message.reply_to_message.text

    if not should_reply or not user_input.strip():
        return

    await client.send_chat_action(message.chat.id, ChatAction.TYPING)
    user_id = message.from_user.id
    
    # ==========================================
    # 👑 3. AI BRAIN (Polite & Smart)
    # ==========================================
    history = await get_user_context(user_id)
    if not history:
        system_prompt = (
            f"You are an advanced, empathetic AI created by THE SHIV (@{Config.OWNER_USERNAME}). "
            "1. NEVER use abuses or bad words. "
            "2. Comfort users if they are sad. "
            "3. Provide accurate answers. "
            "4. If asked for stylish fonts, use Unicode stylized text. "
            "5. Reply in Hindi, Hinglish, or English smoothly."
        )
        history.append({"role": "system", "content": system_prompt})
        
    history.append({"role": "user", "content": user_input})
    
    try:
        ai_reply = await call_openrouter(history)
    except Exception as e:
        await message.reply_text("⚠️ sᴏʀʀʏ sɪʀ! ᴀʟʟ ᴀɪ ɴᴇᴛᴡᴏʀᴋs ᴀʀᴇ ᴄᴜʀʀᴇɴᴛʟʏ ᴅᴏᴡɴ.")
        return

    history.append({"role": "assistant", "content": ai_reply})
    await save_user_context(user_id, history)
    await message.reply_text(ai_reply, quote=True)
